# Generated by Django 3.2.10 on 2022-05-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='updatedat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
